name: CI

on: [push, pull_request]

jobs:
  lint:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.1.0
        name: Install PNPM
        with:
          version: 6
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "pnpm"
          cache-dependency-path: "**/pnpm-lock.yaml"
      - run: pnpm install
      - run: pnpm run lint
